############################
## WireGuard installation ##
############################

---
## Install WireGuard prerequests for Ubuntu

- name: Upgrade system packages on Ubuntu
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Python 2 if not exist
  raw: test -e /usr/bin/python || (apt install -y python-minimal)
  changed_when: false

- name: Install resolvconf if not exist
  raw: test -e /usr/sbin/resolvconf || (apt install -y resolvconf)
  changed_when: false

## Install Wireguard

- name: Install WireGuard
  apt:
    name: wireguard
    state: latest
    install_recommends: no

## Configure WireGuard

- name: Create WireGuard configurations directory
  file:
    dest: /etc/wireguard
    state: directory

- name: Generate WireGuard private and public keys
  shell: |
    set -o pipefail
    umask 077 && wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
  args:
    executable: /bin/bash
  changed_when: false

- name: Register WireGuard private key as a variable
  slurp:
    src: /etc/wireguard/privatekey
  register: wg_privatekey

- name: Generate WireGuard configuration file
  template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
    force: no

- name: Start and enable WireGuard service
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes
